// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-Rr6757pCEeayRdgQIudEwxxkeW-sRaw',
    appId: '1:537374928101:web:69e22917209a49a3d8f80c',
    messagingSenderId: '537374928101',
    projectId: 'finance-advisor-stable',
    authDomain: 'finance-advisor-stable.firebaseapp.com',
    storageBucket: 'finance-advisor-stable.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKE-lLPXTc6PQGTESmnjYwRIduGYxP3Ws',
    appId: '1:537374928101:android:1d0203bf274d9d9fd8f80c',
    messagingSenderId: '537374928101',
    projectId: 'finance-advisor-stable',
    storageBucket: 'finance-advisor-stable.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbekFX1WO726ZSssYCU88-K9z4ZKPNfA0',
    appId: '1:537374928101:ios:59bc5912cb8a8e6ad8f80c',
    messagingSenderId: '537374928101',
    projectId: 'finance-advisor-stable',
    storageBucket: 'finance-advisor-stable.firebasestorage.app',
    iosBundleId: 'com.example.financeAdvisorStable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbekFX1WO726ZSssYCU88-K9z4ZKPNfA0',
    appId: '1:537374928101:ios:59bc5912cb8a8e6ad8f80c',
    messagingSenderId: '537374928101',
    projectId: 'finance-advisor-stable',
    storageBucket: 'finance-advisor-stable.firebasestorage.app',
    iosBundleId: 'com.example.financeAdvisorStable',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-Rr6757pCEeayRdgQIudEwxxkeW-sRaw',
    appId: '1:537374928101:web:ae6e338c90319cffd8f80c',
    messagingSenderId: '537374928101',
    projectId: 'finance-advisor-stable',
    authDomain: 'finance-advisor-stable.firebaseapp.com',
    storageBucket: 'finance-advisor-stable.firebasestorage.app',
  );

}